# Consultar lo dataset

In [12]:
import pandas as pd

In [13]:
dfNotas = pd.read_csv('data/notas.csv')
dfUsuarios = pd.read_csv('data/usuarios.csv')

print(dfNotas.info())
print(dfUsuarios.info())

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             100 non-null    int64
 1   estudiante_id  100 non-null    object
 2   materia        99 non-null     object
 3   nota           100 non-null    object
 4   fecha          11 non-null     object
dtypes: int64(1), object(4)
memory usage: 4.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      120 non-null    object
 1   nombre  118 non-null    object
 2   rol     120 non-null    object
 3   correo  119 non-null    object
dtypes: object(4)
memory usage: 3.9+ KB
None

In [14]:
dfNotas.head(20)

    id estudiante_id    materia        nota       fecha
0    1   matemátic@s          3           5  2023/05/10
1    2      Lengu@@a   aprobado  10-05-2023         NaN
2    3      Hist0ria  excelente       fecha         NaN
3    4      ci3ncias        NaN  2023-03-15         NaN
4    5        Ingles        2.8  2023/11/20         NaN
5    6        ingles          4           5  15-07-2023
6    7       LenguuA       malo  2023/09/12         NaN
7    8   matematicas         -1  2023/02/18         NaN
8    9      ciencias        6.0  2023-04-25         NaN
9   10      historia             2023/08/05         NaN
10  11        lengua          3           2       fecha
11  12   Matematicas             2023/01/30         NaN
12  13      Historia          5           0  2023-06-12
13  14        ingles  excelente  20-11-2023         NaN
14  15      Ciencias          2           7  2023/12/01
15  16        lengua          4  2023/09/10         NaN
16  17   matematicas          3  2023-07-15         NaN
17  18      Hist0ria   aprobado  12-03-2023         NaN
18  19      ci3ncias          2           9       fecha
19  20        Ingles             2023/05/08         NaN

In [ ]:
dfUsuarios.head(20)

   id               nombre         rol                     correo
0   1      Jeffrey Miller   Estudiante         aaron12@hansen.com
1   2        Manuel Davis   Estudiante     destinybrock@gmail.com
2   3   Austin Livingston   Estudiante        jtorres@hotmail.com
3   4       Michael Lopez   Estudiante          omills@taylor.com
4   5       Matthew Marks   Estudiante    bcobb@willis-taylor.com
5   6        Joshua Moore   Estudiante   sarahschmidt@hotmail.com
6   7         Sherry Holt   Estudiante  veronicagonzalez@mata.com
7   8       James Francis   Estudiante         sharon97@yahoo.com
8   9        Melissa Khan   Estudiante      jameswilson@gomez.com
9  10        Steven Scott   Estudiante     xmaldonado@hotmail.com

In [ ]:
# Corregimos el tipo de dato de 'Stock' a entero
dfNotas['nota'] = dfNotas['nota'].astype(bool)

In [17]:
promedio_general = dfNotas['nota'].mean()
dfNotas['nota'].fillna(promedio_general, inplace=True)

TypeError: Could not convert string '510-05-2023fecha2023-03-152023/11/2052023/09/122023/02/182023-04-252023/08/0522023/01/30020-11-202372023/09/102023-07-1512-03-202392023/05/082023-01-1432023/11/2742023/04/092023-02-172023/03/122023/08/302023-09-212023/07/14fecha2023/06/11582023/05/222023/02/09fecha2023/07/012023/10/192023/09/0402023/03/082023/11/232023/05/17fecha2023/06/302023/01/202023/02/152023-09-272023/10/062023/08/142023/03/19fecha2023/12/092023/04/022023/11/282023/02/232023-07-122023/06/082023-10-25fecha2023/08/302023/01/182023/02/052023/03/272023/04/212023/05/09fecha2023/07/022023/09/142023/10/312023/12/192023/02/112023/03/062023/04/17fecha2023/05/132023/06/282023/07/202023/08/222023/09/302023/10/04fecha2023/11/162023/12/082023/01/152023/02/192023/03/212023/04/292023/05/252023/06/142023/07/30fecha2023/08/272023/09/192023/10/122023/11/062023/12/022023/01/092023/02/13' to numeric